<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>BooksWriterStudio</RootNamespace>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.AvaloniaEdit" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <LibraryReference Include="Novolis.Avalonia.GraphicalProfile" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <LibraryReference Include="Novolis.Avalonia.Controls" />
    <LibraryReference Include="Novolis.Avalonia.Layout" />
    <LibraryReference Include="Novolis.Avalonia.Markdown" />
    <LibraryReference Include="Novolis.Avalonia.Manuscript" />
    <PackageReference Include="Novolis.Avalonia.Packaging.Inno">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <LibraryReference Include="Novolis.Avalonia.Studio" />
    <LibraryReference Include="Novolis.Audio.Voice.AzureSpeech" />
    <LibraryReference Include="Novolis.IO.Git" />
    <LibraryReference Include="Novolis.IO.Paths" />
    <LibraryReference Include="Novolis.IO.Recovery" />
    <LibraryReference Include="Novolis.IO.Watching" />
    <LibraryReference Include="Novolis.Manuscript" />
    <LibraryReference Include="Novolis.Manuscript.Editorial" />
    <LibraryReference Include="Novolis.Manuscript.Export.Audio" />
    <LibraryReference Include="Novolis.Manuscript.Export.Pdf" />
    <LibraryReference Include="Novolis.Manuscript.IO" />
    <LibraryReference Include="Novolis.Manuscript.Metrics" />
    <PackageReference Include="WeCantSpell.Hunspell" />
  </ItemGroup>
</Project>
