<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Novolis.Hours.AspireTests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <IsTestingPlatformApplication>true</IsTestingPlatformApplication>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit.Aspire" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Net" />
    <Using Include="Aspire.Hosting.ApplicationModel" />
    <Using Include="Aspire.Hosting.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\NovolisHours\Novolis.Hours.AppHost\Novolis.Hours.AppHost.csproj" />
  </ItemGroup>
</Project>
