<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>ReadAloud.Desktop</RootNamespace>
    <AssemblyName>ReadAloud</AssemblyName>
    <ApplicationTitle>Read Aloud</ApplicationTitle>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ReadAloud\ReadAloud.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Novolis.Manuscript.Export.Audio" />
    <PackageReference Include="Novolis.Avalonia.Mobile.Desktop" />
    <PackageReference Include="Novolis.Logging.Diagnostics" />
    <PackageReference Include="Novolis.Avalonia.Packaging.Inno">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
