<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Novolis.Hours.FeatureTests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <IsTestingPlatformApplication>true</IsTestingPlatformApplication>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\NovolisHours\Novolis.Hours.Domain\Novolis.Hours.Domain.csproj" />
    <ProjectReference Include="..\..\src\NovolisHours\Novolis.Hours.Infrastructure\Novolis.Hours.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\NovolisHours\Novolis.Hours.Server\Novolis.Hours.Server.csproj" />
  </ItemGroup>
</Project>
