<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Novolis.Reach.Transport</RootNamespace>
    <AssemblyName>Novolis.Reach.Transport</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Reach.Protocol\Reach.Protocol.csproj" />
  </ItemGroup>
  <ItemGroup>
    <LibraryReference Include="Novolis.Transports.Abstractions" />
    <LibraryReference Include="Novolis.Transports.Quic" />
    <LibraryReference Include="Novolis.Transports.Tcp" />
    <LibraryReference Include="Novolis.Transports.Udp" />
    <LibraryReference Include="Novolis.Transports.Framing" />
  </ItemGroup>
</Project>
