<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Novolis.Hours.UiTests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <IsTestingPlatformApplication>true</IsTestingPlatformApplication>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="TUnit.Playwright" />
    <LibraryReference Include="Novolis.Testing.Playwright" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\NovolisHours\Novolis.Hours.Client.Blazor\Novolis.Hours.Client.Blazor.csproj" />
    <ProjectReference Include="..\..\src\NovolisHours\Novolis.Hours.Client.Presentation\Novolis.Hours.Client.Presentation.csproj" />
    <ProjectReference Include="..\..\src\NovolisHours\Novolis.Hours.Client\Novolis.Hours.Client.csproj" />
    <ProjectReference Include="..\..\src\NovolisHours\Novolis.Hours.Server\Novolis.Hours.Server.csproj" />
  </ItemGroup>
</Project>
