<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>Novolis.Reach.Client.Windows</RootNamespace>
    <AssemblyName>Novolis.Reach.Client.Windows</AssemblyName>
    <ApplicationTitle>Novolis Reach</ApplicationTitle>
    <NoWarn>$(NoWarn);CS0618</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <LibraryReference Include="Novolis.Reach.Client" />
    <LibraryReference Include="Novolis.Avalonia.Reach" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Avalonia.Desktop" />
    <LibraryReference Include="Novolis.Avalonia.GraphicalProfile" />
    <LibraryReference Include="Novolis.Avalonia.Mobile.Desktop" />
    <PackageReference Include="Novolis.Avalonia.Packaging.Inno" />
    <LibraryReference Include="Novolis.Video.Abstractions" />
    <LibraryReference Include="Novolis.Video.Codecs.H264" />
    <PackageReference Include="NAudio" />
  </ItemGroup>
</Project>
