<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SinsOfACapitalismTycoon.Unit</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="Novolis.Economy.Logistics" />
    <PackageReference Include="Novolis.MachineLearning.Neural" />
    <PackageReference Include="Novolis.MachineLearning.Neural.Abstractions" />
    <PackageReference Include="Novolis.Simulation.Mesh" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SinsOfACapitalismTycoon\SinsOfACapitalismTycoon.csproj" />
  </ItemGroup>
</Project>
