<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Novolis.Apps.Manifest.Unit</RootNamespace>
    <AssemblyName>Novolis.Apps.Manifest.Unit</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\tools\AppsManifest\AppsManifest.csproj" />
  </ItemGroup>
</Project>
