<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>BooksMobile.Desktop</RootNamespace>
    <AssemblyName>BooksMobile</AssemblyName>
    <ApplicationTitle>Books Mobile</ApplicationTitle>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BooksMobile\BooksMobile.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Novolis.Avalonia.Mobile.Desktop" />
    <PackageReference Include="Novolis.Avalonia.Packaging.Inno">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
