#Requires -Version 7.0
param(
    [Parameter(Mandatory = $true)]
    [string]$AppVersion,
    [Parameter(Mandatory = $true)]
    [string]$PublishDir,
    [Parameter(Mandatory = $true)]
    [string]$OutputDir,
    [Parameter(Mandatory = $true)]
    [string]$ScriptPath
)

$ErrorActionPreference = 'Stop'

$publishDir = $PublishDir.Replace('/', '\')
$outputDir = $OutputDir.Replace('/', '\')
$outputBase = "ManuscriptStudioSetup-$AppVersion-win-x64"

$lines = @(
    '; Manuscript Studio installer (generated by novolis-apps)'
    '[Setup]'
    'AppId=Novolis.ManuscriptStudio'
    'AppName=Manuscript Studio'
    "AppVersion=$AppVersion"
    'DefaultDirName={localappdata}\Programs\Novolis\Manuscript Studio'
    'DefaultGroupName=Manuscript Studio'
    "OutputBaseFilename=$outputBase"
    "OutputDir=$outputDir"
    'PrivilegesRequired=lowest'
    'DisableProgramGroupPage=yes'
    'WizardStyle=modern'
    'ArchitecturesAllowed=x64compatible'
    'ArchitecturesInstallIn64BitMode=x64'
    'Compression=lzma2'
    'SolidCompression=yes'
    'UninstallDisplayIcon={app}\ManuscriptStudio.exe'
    '[Tasks]'
    'Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"; Flags: unchecked'
    '[Files]'
    "Source: `"$publishDir\*`"; DestDir: `"{app}`"; Flags: ignoreversion recursesubdirs createallsubdirs"
    '[Icons]'
    'Name: "{autoprograms}\Manuscript Studio"; Filename: "{app}\ManuscriptStudio.exe"'
    'Name: "{autodesktop}\Manuscript Studio"; Filename: "{app}\ManuscriptStudio.exe"; Tasks: desktopicon'
    '[Run]'
    'Filename: "{app}\ManuscriptStudio.exe"; Description: "Launch Manuscript Studio"; Flags: nowait postinstall skipifsilent'
)

New-Item -ItemType Directory -Force -Path (Split-Path $ScriptPath -Parent) | Out-Null
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($ScriptPath, ($lines -join "`r`n") + "`r`n", $utf8NoBom)
