<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>BooksMobile</RootNamespace>
    <AssemblyName>BooksMobile.Shared</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.AvaloniaEdit" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <LibraryReference Include="Novolis.Audio.Voice.AzureSpeech" />
    <LibraryReference Include="Novolis.Avalonia.Speech" />
    <LibraryReference Include="Novolis.Avalonia.Layout" />
    <LibraryReference Include="Novolis.Avalonia.Markdown" />
    <LibraryReference Include="Novolis.Avalonia.Manuscript" />
    <LibraryReference Include="Novolis.Avalonia.Mobile" />
    <LibraryReference Include="Novolis.IO.GitHub" />
    <LibraryReference Include="Novolis.Manuscript" />
    <LibraryReference Include="Novolis.Manuscript.Export.Audio" />
    <LibraryReference Include="Novolis.Manuscript.IO" />
    <PackageReference Include="Octokit" />
  </ItemGroup>
</Project>
