<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>DraftStudio.Unit</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="Novolis.Avalonia.Cad" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\DraftStudio\DraftStudio.csproj" />
  </ItemGroup>
</Project>
